# Generated by Django 2.1.5 on 2019-12-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rockets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='manufacture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rockets.Manufacture'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='manufacture',
            field=models.CharField(max_length=300),
        ),
    ]
