# Generated by Django 2.1.5 on 2019-12-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockets', '0002_auto_20191227_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('orbit', models.CharField(choices=[('Low Orbit', 'Low Orbit'), ('Geostationary Orbit', 'Geostationary Orbit'), ('High Orbit', 'High Orbit'), ('Moon', 'Moon'), ('Mars', 'Mars')], default='orbit', max_length=200)),
                ('site', models.CharField(choices=[('Baikonur', 'Baikonur'), ('Plesetsk', 'Plesetsk'), ('Cape Canaveral', 'Cape Canaveral'), ('Vanderberg', 'Vanderberg'), ('Jiuquan', 'Jiuquan')], default='site', max_length=200)),
                ('customerName', models.CharField(max_length=500)),
                ('note', models.TextField()),
            ],
        ),
    ]
